### ISSUE TITLE
How to compute score?

### ISSUE THREAD

**Issue by monacofj** [courselab/ttsnake#35]
Number of blocks / time during the game play seems straightforward.
However, if I start the game, play for one second and eat 1 block, I will score 100%.
Perhaps more than another player who has played for 10 seconds and eaten 9 blocks (the longer one plays, the harder the game gets). I would like to hear other opinions.

Perhaps the score could include blocks/time and also snake length?

Or it could be a multi-parameter score: block/time, sname length, other statistc...

**Comment by JayroBoy** [comment]
I've been thinking about this and I don't think we should include time in the score. In this game, specifically, taking a long time can mean that either you're bad at the game(and can't aim the snake) or you're very good(and survived for a long time). Since time is ambivalent, I don't think there's a reliable way of adding it to the score without being unfair. Most snake games I've played would treat your score as some multiple of the number of energy blocks you ate. An interesting alternative would be to make different types of energy blocks that have different values(Like the nokia version that had foods worth different amounts of points), but I think the calculation should be more straightforward and shouldn't involve divisions

**Comment by monacofj** [comment]
@JayroBoy, perhaps a way to handle game-time ambivalence, might be to cause the snake to gain energy when it eats and to lose energy when it moves (an energy bar would be nice). If the snake wanders too long without eating, it will eventually die. Poor players who can't catch blocks are naturally penalized.  We might show several parameters: elapsed time, block count, distance traveled etc.  Then, we can compute different scores: blocks/time, efficience (blocks / distance) etc.

**Comment by matheushjs** [comment]
I think ultimately what matters is the number of blocks you ate. But I do like the idea of computing multiple scores.

**Comment by monacofj** [comment]
Reasoning furhter, I agree with @matheushjs. If snake grows as it eats and loses energy as it moves, the number of eaten blocks reflects the overall player performance, as it captures dexterity and time in one single metric.

**Comment by monacofj** [comment]
Closing as it may be further discussed in #48
