### ISSUE TITLE
Increase number of energy blocks to be eaten

### ISSUE THREAD

**Issue by matheushjs** [courselab/ttsnake#41]
Right now the game has only 5 energy blocks, and there is nothing else to do after you eat them.

Therefore it is a boring game thus far.

You should increase the number of energy blocks, and possibly make them appear one after another, as the snake eats them. 
Right now they are all presented on the board, which will become a hassle for a larger number of blocks.

**Comment by JayroBoy** [comment]
I'm gonna assign this one to myself and give it a go

**Comment by monacofj** [comment]
How about a new block appearing right after one has been eaten, so that there are always MAX_ENERGY_BLOCKS?

The game becomes more difficult as it proceeds because the snake gets longer and it becomes harder and harder not to beat its own tail.

**Comment by JayroBoy** [comment]
In retrospect, this does seem more intuitive. I'll try to tinker around with the code to do it that way, shouldn't be too difficult.

**Comment by matheushjs** [comment]
Reopening due to the ongoing discussion
(closed automatically with the pull request)

**Comment by matheushjs** [comment]
My opinion is that the current way is better.

If there are always K blocks on the screen, the user will never risk themselves to eat a block that is on the border, which is more difficult.

**Comment by JayroBoy** [comment]
I think that's not exactly the case. I played around a bit after implementing it and sure enough, I did that for a while. What eventually happened is that as I kept eating the blocks near the center, since only the eaten blocks respawn, eventually the blocks started to get closer and closer to the border, until the 3 blocks on screen were on the top border. Since the number of blocks on screen is so small, should the player opt for that strategy, eventually they will have to make up to 3 risky moves in a row, which is harder than doing just the one and then another after some time. This strategy is also bad for your score, since forgoing a nearer block because it is closer to the border will increase your overall time, which is inversely proportional to your score. Some of the changes proposed in #48, such as killing the snake if it goes below a certain score, would also curb this strategy greatly.
