### ISSUE TITLE
How energy is spent

### ISSUE THREAD

**Issue by monacofj** [courselab/ttsnake#62]
Currently, energy is spent only when WASD is pressed. Steady movement does not consume energy.
Is the desired behavior? I was expecting otherwise, but opinions may vary...

**Comment by Alecxannder-Sonnenberg** [comment]
Losing energy over a period of time seems more mechanically intuitive in my opinion, having a change in direction cost energy creates some challenges in development, we would need to make sure energy blocks always spawn in a way the player can get to them or else he may lose the game not because of a lack of skill but due to dumb luck.

**Comment by monacofj** [comment]
> Losing energy over a period of time seems more mechanically intuitive in my opinion,

Agree.

> having a change in direction cost energy creates some challenges in development, 

It seems (?) that current implementation is like this. Is it?

> we would need to make sure energy blocks always spawn in a way the player can get to them or else he may lose the game not because of a lack of skill but due to dumb luck.

It makes sense. Perhaps forcing one block per quadrant would help?

**Comment by matheushjs** [comment]
> Losing energy over a period of time seems more mechanically intuitive in my opinion,

Agree, but time measured in game ticks, rather than seconds. Otherwise the game will become easier when the snake is fast.

> Perhaps forcing one block per quadrant would help?

I think the luck part only makes the game better. I would like to see the game with the new energy handling before forcing one block per quadrant. I expect the game to be fun without it.

**Comment by monacofj** [comment]
Closing as it seems to be handled in #72.
