### ISSUE TITLE
Starting in menu screen

### ISSUE THREAD

**Issue by brudel** [courselab/ttsnake#65]
How about the game opens on the menu screen rather than in gameplay?

**Comment by matheushjs** [comment]
So every time I want to play, I have to select the settings?

I know that since we are developers, we love settings, but it is generally a bad idea to present a dense interface cluttered with settings to the average user. It goes against principles like [convention over configuration](https://en.wikipedia.org/wiki/Convention_over_configuration) and [Keep it Simple Stupid](https://en.wikipedia.org/wiki/KISS_principle). See also [95% of the people stick to the default option](https://service-design.co/95-of-the-people-stick-to-the-default-option-9e16316a64e1).

I would rather keep it the way it is, and implement a way to persist the user settings in a file, so that they are restored the next time they play the game.

**Comment by brudel** [comment]
@matheushjs Good points. When I made this issue I was thinking that, if one wants to play with no default settings, feels a little weird need to enter the game, quit the party to change settings, and go back.

But both this idea of persisting the user settings, or even a future proper initial menu really seems better options to solve this question.

**Comment by matheushjs** [comment]
Maybe an initial menu with options "Play" and "Settings" as is usual. It is much less intimidating

**Comment by brudel** [comment]
Yes, together with settings persistency, would be nice

**Comment by monacofj** [comment]
Closed by #67
